### ISSUE TITLE
createEvent is not working

### ISSUE THREAD

**Issue by westy92** [warbrett/node-cronofy#4]
In createEvent, the wrapper is posting to https://api.cronofy.com/v1/calendars instead of https://api.cronofy.com/v1/calendars/__calendarId__/events, resulting in an error.

View the API docs at: https://www.cronofy.com/developers/api/#upsert-event

**Comment by westy92** [comment]
I submitted a pull request: https://github.com/warbrett/node-cronofy/pull/5.

**Comment by warbrett** [comment]
Merged! Thanks for the help!

**Comment by westy92** [comment]
You're welcome!  What is the process for updating npm?

**Comment by warbrett** [comment]
Just published, sometimes their cache takes a bit but if you manually set your version to 1.04 in your package.json you should get it.

**Comment by westy92** [comment]
Got it, thank you!
