### ISSUE TITLE
Small typo in documentation for refreshAccessToken()

### ISSUE THREAD

**Issue by lafersousa** [warbrett/node-cronofy#8]
The documentation for refreshAccessToken() lists the options as follows:

Options Object
client_id - Your client id.
client_secret - Your client secret.
grant_type - a string of "refresh_token".
**refresh_Token** - The refresh token for the user.

However the refresh token must be passed in as **refresh_token** or the request will fail.

**Comment by warbrett** [comment]
Fixed, 
Thank you for catching/reporting this!

**Comment by lafersousa** [comment]
No problem! I'll be happy to provide any feedback as I work with the
library, thanks for putting it together! So far it has been really helpful
to getting integrated with Cronofy quickly.

One other quick thing on the typo, its also on the npm page (
https://www.npmjs.com/package/cronofy), which is actually where I first
copied the code from.
